title: Tapia 2018 Doctoral Consortium
show_downloads: false


description: "<small>
<b>Lunch:</b> 12pm - 1pm  <br/>
<br/>
<b>Opening/Intro:</b> 1pm - 1:30pm <br/>
<b>Session 1:</b> 1:30pm - 2:10pm <br/>
<b>Session 2:</b> 2:10pm - 2:50pm <br/>
<br/>
<b>Coffee Break</b> <br/>
<br/>
<b>Session 3:</b> 3:05pm - 3:45pm <br/>
<b>Session 4:</b> 3:45pm - 4:25pm <br/>
<br/>
<b>Break</b> <br/>
<br/>
<b>Discussion:</b> 4:35pm - 4:50pm <br/>
<b>Closing:</b> 4:50pm - 5:00pm <br/>
<br/> 
</small>"


theme: jekyll-theme-minimal
