title: Tapia 2018 Doctoral Consortium
show_downloads: false


description: "<small>
<b>Lunch:</b> 12p - 1p  <br/>
<br/>
<b>Opening/Intro:</b> 1p - 1:30p <br/>
<b>Session 1:</b> 1:30p - 2:10p <br/>
<b>Session 2:</b> 2:10p - 2:50p <br/>
<br/>
<b>Coffee Break</b> <br/>
<br/>
<b>Session 3:</b> 3:05p - 3:45p <br/>
<b>Session 4:</b> 3:45p - 4:25p <br/>
<br/>
<b>Break</b> <br/>
<br/>
<b>Discussion:</b> 4:35p - 4:50p <br/>
<b>Closing:</b> 4:50p - 5:00p <br/>
<br/> 
</small>"


theme: jekyll-theme-minimal
